# Generated by Django 2.2.4 on 2020-06-06 00:05

from django.db import migrations, models
import django.db.models.deletion
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0118_auto_20200605_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('address', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('profile', models.OneToOneField(help_text='User profile for this personal token', on_delete=django.db.models.deletion.CASCADE, related_name='personal_token', to='dashboard.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
